CREATE TABLE IF NOT EXISTS urls (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS url (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code_request BIGINT,
    h1 TEXT,
    title TEXT,
    descriptions TEXT,
    created_at TIMESTAMP
);